provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  newpythonhmac:
    lang: python3
    handler: ./newpythonhmac
    image: martindekov/newpythonhmac:latest
    environment:
      write_debug: true
